name: 'Projektor'
description: 'Publish test results to Projektor for easy viewing'
inputs:
  config-file:
    description: 'Path to Projektor config file'
    default: 'projektor.json'
    required: false
  server-url:
    description: 'Projektor server URL to publish results to'
    required: false
  results:
    description: 'Paths to the test results XML files'
    required: false
  attachments:
    description: 'Paths to the files to attach to the test report'
    required: false
  coverage:
    description: 'Paths to test coverage files to include in test report'
    required: false
  performance:
    description: 'Paths to performance test files to include in test report'
    required: false
  compression-enabled:
    description: 'Whether to enable compressing results when sending them to server to improve performance'
    required: false
  token:
    description: 'Token for publishing results to Projektor server if server has token enabled'
    required: false
  print-link:
    description: 'Set to "true" to log report URL from previously-created report for easy access'
    required: false
  project-name:
    description: 'Project name when publishing multiple Projektor reports from the same repo'
    required: false
outputs:
  report-url:
    description: 'Link to Projektor test report'
runs:
  using: 'node12'
  main: 'dist/index.js'
