name: Tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: test
        run: |
          npm install
          npm run-script test

      - name: Projektor publish
        uses: craigatk/projektor-action@v15.0.1
        with:
          server-url: https://projektorlive.herokuapp.com
          results: test-results/*.xml
          coverage: coverage/*.xml
          token: ${{ secrets.PROJEKTOR_TOKEN }}
